### ISSUE TITLE
Investigate Edge extension ownership of networking related integration testing

### ISSUE THREAD

**Issue by timkimadobe** [adobe/aepsdk-edge-android#107]
Linked to https://github.com/adobe/aepsdk-edge-ios/issues/408

### Task description

Need to investigate the use cases across extensions that depend on Edge Network extension, and see if it is sufficient for Edge Network extension to own all networking related integration testing cases. That is, the ones dealing with `NetworkRequest` and `HttpConnection`

**Comment by emdobrin** [comment]
Solved as part of iOS, Edge extension will be testing the APIs contract overall, and other Edge extensions may choose to do additional testing with request/response asserts as needed.
